S10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='social_app/socialindex.html'), name='social_app'),
    path('logout/', LogoutView.as_view(), name='logout'),    
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('djangoaccounts/', include('users.urls'), name='djangoaccounts'),


]

dashboard/urls.py
from django.urls import path, include
from .views import index

app_name='dashboard'


urlpatterns = [
    path('', index, name='index')

]

users/urls.py
from django.urls import path, include
from .views import index, django_signup, django_login
from django.conf.urls import url

app_name = 'djangoaccounts'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', django_signup, name='signup'),
    path('login/', django_login, name='login'),
]

dashboard/models.py
from django.db import models

# Create your models here.

social_app/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     image = models.ImageField(default='default.jpg', upload_to='profile_pics')

#     def __str__(self):
#         return f'{self.user.username} Profile'

#     def save(self):
#         super().save()

#         img = Image.open(self.image.path)

#         if img.height > 300 or img.width > 300:
#             output_size = (300, 300)
#             img.thumbnail(output_size)
#             img.save(self.image.path)

users/forms.py
from django import forms
# from django.utils.timezone import now
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)

class UserForm(forms.Form):
    username = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={
            'class':'inputText',
            'placeholder': 'Unique username'
            })
        )
    password = forms.CharField(
        max_length=20, 
        widget=forms.PasswordInput(attrs={
            'class':'inputText',
            'placeholder': 'Your highly classified password'
            })
        )

    class Meta:
        model = User
        fields = ['username','password']


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=150, required=False)
    email = forms.EmailField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', ]

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='../')
def index(request):
    return render(request, 'dashboard/dashboard.html')

social_app/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import redirect, render, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import UserForm, UserCreateForm
from django.contrib import messages
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponse


def index(request):
    if request.method == "GET":
        return render(request, "users/djaccindex.html")
        
def django_signup(request):
    f = UserCreateForm(request.POST)
    context = {
        'signupform': f
    }
    if request.method == "GET":
        return render(request, "users/djaccsignup.html", context)
    if request.method == 'POST':
        if f.is_valid():
            f.save()
            username = request.POST['username']
            password1 = request.POST['password1']
            context = {
                'username': username,
                'password': password1
            }
            return render(request, "users/djacclogin.html", context) 
    else:
        f = UserCreateForm()
 
    return render(request, 'users/djaccsignup.html', context)
    
    # context = {
    #     'signupform': CustomUserCreationForm()
    # }
    # if request.method == "GET":
    #     return render(request, "users/djaccsignup.html", context)
    # if request.method == 'POST':
    #     password1 = request.POST['password1']
    #     password2 = request.POST['password2']
    #     if password1 != password2:
    #         context['error'] = "Please check your typing, it doesn't match."
    #         return render(request, "users/djaccsignup.html", context)
    #     else:
    #         username = request.POST['username']
    #         user = User.objects.create_user(username=username, password=password1)
    #         context = {
    #             'username': user.username,
    #             'password': password1
    #         }
    #         return render(request, "users/djacclogin.html", context)

def django_login(request):            
    context = {
        'loginform': UserForm()
    }
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if(user is not None):
            request.session['username'] = username
            login(request, user)
            request.method = "GET"
            return redirect(reverse('dashboard:index'))
        else:
            return render(request, "users/djacclogin.html", context)
    return render(request, "users/djacclogin.html", context)

social_app/templates/social_app/socialindex.html
{% load socialaccount %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Get Started</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Get Started</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <div class="greeting">
                <h3>What are you doing here? You're already logged in, {{user.username}} !</h3>
            </div>
            <a class="cta-white btn" href="{% url 'dashboard:index'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}
            <div class="greeting">
                <h3>Hello there, have I seen you before?</h3>
            </div>
            <a class="cta-green btn" href="{% url 'djangoaccounts:index' %}">Login with Django Account</a>
            <a class="cta-white btn" href="{% provider_login_url 'google' %}">Login with Google</a> {% endif %}
        </div>
    </section>
</body>

</html>

templates/dashboard/dashboard.html
{% load socialaccount %} {% load static %}

<html>

<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <title>Dashboard</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Dashboard</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <br>
            <h3>Information:</h3>
            <p>First Name: {{ user.first_name }} </p>
            <p>Last Name: {{ user.last_name }} </p>
            <p>Email: {{ user.email }} </p>

            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %} {% endif %}

        </div>
    </section>
</body>

</html>

templates/users/djaccindex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Django Accounts</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:index'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}
            <h2>Hello there, have I seen you before?</h2>
            <a class="cta-green btn" href="{% url 'djangoaccounts:signup' %}">Sign-up with Django</a>
            <a class="btn" href="{% url 'djangoaccounts:login' %}">Login with Django</a> {% endif %}
        </div>
    </section>

</body>

</html>

templates/users/djacclogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account Login</title>
</head>

<body>

    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Django Accounts</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:index'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}
            <h2>Join us, newbie!</h2>
            <form class="flexrow-llcl" action="{% url 'djangoaccounts:login' %}" method="post">
                {% csrf_token %} {% if form != None %} {{loginform}} {% else %}
                <br>
                <label for="username">Username: </label>
                <input id="id_username" type="text" name="username" placeholder="Unique username" value="{{ username }}" required>
                <label for="password">Password: </label>
                <input id="id_password" type="password" name="password" placeholder="Classified password" value="{{ password }}" required> {% endif %}
                <input type="submit" class="loginbtn cta-green btn" value="Login!">

            </form>{% endif %}
        </div>
    </section>
</body>

</html>

templates/users/djaccsignup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account Registration</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Django Accounts</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:index'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}
            <h2>Join us, newbie!</h2>

            <form class="flexrow-llcl" action="/djangoaccounts/signup/" method="post">
                {% csrf_token %} {% for field in signupform %}
                <h5>{{ field.label_tag }}</h5>
                <p>{{ field }}</p>
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small><br> {% endif %}{% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %} <br>{% endfor %}
                <input type="submit" class="createaccount cta-green btn" value="Create Account!">

            </form>
            <a href="/djangoaccounts/login/">
                <p>Already have one?</p>
            </a>
            {% endif %}
        </div>
    </section>

</body>

</html>